### ISSUE TITLE
Improve landscape mode

### ISSUE THREAD

**Issue by xmha97** [JahidHasanCO/BMI-Calculator#11]
Hi,
Please improve landscape mode.

![Screenshot_2022-11-24-15-56-38-182_dev.jahidhasanco.bmicalculator.jpg](https://user-images.githubusercontent.com/23485114/203784398-c6259ce3-4a57-4d17-b6fd-0da9d3e671cc.jpg)

**Comment by JahidHasanCO** [comment]
Hi @xmha97,
Thanks for contracting me. I will improve this on my available time.  😀

**Comment by xmha97** [comment]
Thanks.

**Comment by JahidHasanCO** [comment]
Hi @xmha97 I have changed this code and fix bugs.

**Comment by JahidHasanCO** [comment]
![Screenshot_20221125-142909_BMI Calculator](https://user-images.githubusercontent.com/50579963/203936054-7b48b5b7-b230-407c-88d7-4182d99c3f6d.jpg)


![Screenshot_20221125-142925_BMI Calculator](https://user-images.githubusercontent.com/50579963/203936082-f16ce93c-1e3d-491f-b5f2-2b7c8c70a770.jpg)

**Comment by xmha97** [comment]
Wow, this is really awesome.

**Comment by xmha97** [comment]
@JahidHasanCO 
Wow, this is really awesome.
But please fix all content to screen without scroll.
On landscape mode, I can't select age.

**Comment by JahidHasanCO** [comment]
@xmha97 Ok. I will fix this.

**Comment by xmha97** [comment]
> @xmha97 Ok. I will fix this.

Thanks.
