### ISSUE TITLE
versionName & versionCode not updated

### ISSUE THREAD

**Issue by IzzySoft** [JahidHasanCO/BMI-Calculator#17]
Please remember to update `versionCode` (must be increased, as Android uses this to tell versions apart) and `versionName` (should ideally match the tag name) in your [`build.gradle`](https://github.com/JahidHasanCO/BMI-Calculator/blob/master/app/build.gradle.kts#L14) before tagging a new release. Currently, that's a bit confusing: tag `1.0.1` is titled `BMI Calculator v1.0.4` but has an APK attached that identifies as 1.0+1 :zany_face: Moreover, with the `versionCode` unchanged, Android considers that the same version as the previous release.

Thanks in advance!

**Comment by JahidHasanCO** [comment]
@IzzySoft Hi Sir,

Thanks for letting know 😊. I was forgot about change the versionCode and versionName. And release title  was a little bit typing mistake 🤪. I will update those. 

Again, Thanks for pay attention on this matter ❤.

**Comment by IzzySoft** [comment]
Gladly – and thanks for the fast reaction and fix! If you wonder how I noticed: The updater of my repo informed me. Your app is [listed here](https://apt.izzysoft.de/fdroid/index/apk/dev.jahidhasanco.bmicalculator), so in case you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme, be welcome! Also if you'd like me to provide the description etc. set up there via PR as [Fastlane structure](https://gitlab.com/-/snippets/1895688) so you can control how your app is presented (would be pulled along with updates to the app when available), just say so.

**Comment by JahidHasanCO** [comment]
> Gladly – and thanks for the fast reaction and fix! If you wonder how I noticed: The updater of my repo informed me. Your app is [listed here](https://apt.izzysoft.de/fdroid/index/apk/dev.jahidhasanco.bmicalculator), so in case you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme, be welcome! Also if you'd like me to provide the description etc. set up there via PR as [Fastlane structure](https://gitlab.com/-/snippets/1895688) so you can control how your app is presented (would be pulled along with updates to the app when available), just say so.

Thanks @IzzySoft , I will provide the description.

**Comment by IzzySoft** [comment]
Can you please give me a ping when the fixed release is available? I have to disable updates for now due to the `versionName` issue (or rather put them to monthly instead of daily).

**Comment by JahidHasanCO** [comment]
@IzzySoft I am not updating yet I was just tried to build CI CD pipeline.

**Comment by IzzySoft** [comment]
No complaints, just let me know **when** it's ready so I set the update check to daily again :wink: Currently I can't as it needlessly would pull the same APK over and again. Thanks!
