### ISSUE TITLE
Sync theme with OS Theme

### ISSUE THREAD

**Issue by xmha97** [JahidHasanCO/BMI-Calculator#18]
Please add the dark theme and enable the sync theme with the OS theme.

![Screenshot_2022-12-04-13-19-15-000_dev.jahidhasanco.bmicalculator.jpg](https://user-images.githubusercontent.com/23485114/205484359-d8b5bab2-996a-46b1-b2e4-11c599f884f0.jpg)

![Screenshot_2022-12-04-13-19-22-700_dev.jahidhasanco.bmicalculator.jpg](https://user-images.githubusercontent.com/23485114/205484361-fa14b1dc-89ec-43a0-ba94-52cedc4d3e2f.jpg)

**Comment by JahidHasanCO** [comment]
Hi @xmha97 thanks for this issue. it will be fix on next update.

**Comment by JahidHasanCO** [comment]
![Screenshot_20230317-182817_BMI Calculator](https://user-images.githubusercontent.com/50579963/225905702-7ce77b8e-8f70-4b03-8110-ae3ee6e44bb6.jpg)

**Comment by xmha97** [comment]
> ![Screenshot_20230317-182817_BMI Calculator](https://user-images.githubusercontent.com/50579963/225905702-7ce77b8e-8f70-4b03-8110-ae3ee6e44bb6.jpg)
> 

Wow, that's very nice 👍
Thanks 🙏
