### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [JahidHasanCO/BMI-Calculator#20]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-03-17-16-56-56-995_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/225918127-ca15048d-6ca6-42af-9ad5-fd3f15ba063c.jpg)

**Comment by JahidHasanCO** [comment]
@xmha97 material you have been implemented. Please let me know if there is any error.

**Comment by xmha97** [comment]
Thanks 🙏
Please release a new version to GitHub.

**Comment by JahidHasanCO** [comment]
New version released on GitHub.

**Comment by JahidHasanCO** [comment]
Hi @xmha97 
Monochrome themed icon has fix on version 1.0.3
[Check Here](https://github.com/JahidHasanCO/BMI-Calculator/releases/tag/1.0.3)

**Comment by xmha97** [comment]
Thanks 🙏
